name: Get latest push on lotus repo
on:
  push
  # schedule:
  #   - cron: "0 6,12,18,23 * * *"

jobs:
  get-push-date:
    runs-on: ubuntu-latest
    outputs:
      isPushed: ${{ steps.git-check.outputs.pushed}}
    steps:
      - name: Fetch latest push
        id: filecoin-lotus
        run: |
          echo ::set-output name=push_tag::$(curl -sL https://api.github.com/repos/Vojimirovich/action-target | jq -r ".pushed_at")
          echo ::set-output name=current_tag::$(cat ./filecoin-lotus-latest-push-date.txt)
      - name: Check if new push
        id: git-check
        if: steps.filecoin-lotus.outputs.current_tag != steps.filecoin-lotus.outputs.push_tag
        run: echo "::set-output name=pushed::true" && truncate -s 0 filecoin-lotus-latest-push-date.txt && echo ${{steps.filecoin-lotus.outputs.push_tag}} >> filecoin-lotus-latest-push-date.txt && cat filecoin-lotus-latest-push-date.txt;

  run-test-crawler:
    needs: [get-push-date]
    runs-on: ubuntu-latest
    if: needs.get-push-date.outputs.isPushed == 'true'
    steps:
      # Checkout the repository.
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: chore/generate-tests
          commit-message: Update tests.json
          title: "chore(test-crawler): Update tests.json"
          delete-branch: true
