name: Get latest push on lotus repo
on:
  push
  # schedule:
  #   - cron: "0 6,12,18,23 * * *"

jobs:
  get-push-date:
    runs-on: ubuntu-latest
    outputs:
      isPushed: ${{ steps.git-check.outputs.pushed}}
    steps:
      # Checkout the repository.
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Store/Restore file in cache
        if: steps.updateCachedFile.outputs.cache-hit != 'true'
        id: cachedFile
        uses: actions/cache@v2
        with:
          path: filecoin-lotus-latest-push-date.txt
          key: ${{ runner.os }}-latest-push-date-${{ hashFiles('filecoin-lotus-latest-push-date.txt') }}

      - name: Create last push file if not cached
        if: steps.cachedFile.outputs.cache-hit != 'true'
        run: echo "initialDate" >> filecoin-lotus-latest-push-date.txt

      - name: Fetch latest push
        id: filecoin-lotus
        run: |
          echo ::set-output name=push_tag::$(curl -sL https://api.github.com/repos/Vojimirovich/action-target | jq -r ".pushed_at")
          echo ::set-output name=current_tag::$(cat filecoin-lotus-latest-push-date.txt)

      - name: Check tags
        run: echo ${{steps.filecoin-lotus.outputs.current_tag}} and ${{steps.filecoin-lotus.outputs.push_tag}}

      - name: Check if new push
        id: git-check
        if: steps.filecoin-lotus.outputs.current_tag != steps.filecoin-lotus.outputs.push_tag
        run: echo "::set-output name=pushed::true" && truncate -s 0 filecoin-lotus-latest-push-date.txt && echo ${{steps.filecoin-lotus.outputs.push_tag}} >> filecoin-lotus-latest-push-date.txt && cat filecoin-lotus-latest-push-date.txt;

      - name: Store file in cache
        id: updateCachedFile
        uses: actions/cache@v2
        with:
          path: filecoin-lotus-latest-push-date.txt
          key: ${{ runner.os }}-latest-push-date-${{ hashFiles('filecoin-lotus-latest-push-date.txt') }}

      - name: check version
        run: cat filecoin-lotus-latest-push-date.txt
  run-test-crawler:
    needs: [get-push-date]
    runs-on: ubuntu-latest
    if: needs.get-push-date.outputs.isPushed == 'true'
    steps:
      - name: Check
        run: echo "doooo"
